version: "3.7"
services:
  # GERENCIADOR DE CONTAINERS
  portainer:
    image: portainer/portainer:latest
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainerdata:/data
    networks:
      - aws

  backend:
    build: "./"
    restart: always
    privileged: true
    ports:
      - "3000:3000"
    networks:
      - aws

networks:
  aws:
    driver: overlay

volumes:
  portainerdata:
